"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { FileText, Loader2, MessageSquareWarning, RotateCcw, Star } from "lucide-react";
import { toast } from "sonner";

import { AdminDataToolbar, AdminMetricCard, AdminStatusPill } from "@/components/sections/admin-commerce-ui";
import { AdminPageHeader } from "@/components/sections/admin-page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { AdminListResponse } from "@/lib/admin-types";
import { apiRequest } from "@/lib/api-client";
import type { ArticleItem, ComplaintItem, ReturnRequestItem, ReviewItem } from "@/lib/trust-types";

function useAdminList<T>(path:string){
  const [data,setData]=useState<AdminListResponse<T>|null>(null);const [search,setSearch]=useState("");const [status,setStatus]=useState("ALL");const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{try{setData(await apiRequest(`${path}?q=${encodeURIComponent(search)}&status=${status}&pageSize=100`));}catch(e){toast.error(e instanceof Error?e.message:"Data admin gagal dimuat.");}finally{setLoading(false);}},[path,search,status]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),200);return()=>clearTimeout(timer);},[load]);return{data,search,setSearch,status,setStatus,loading,load};
}
const options=(values:string[])=>values.map(value=>({label:value,value}));

export function AdminReviewsPageClient(){
  const list=useAdminList<ReviewItem>("/api/admin/reviews");async function mutate(id:string,status:"PUBLISHED"|"HIDDEN"){try{await apiRequest(`/api/admin/reviews/${id}`,{method:"PATCH",body:JSON.stringify({status})});toast.success("Review dimoderasi.");await list.load();}catch(e){toast.error(e instanceof Error?e.message:"Moderasi gagal.");}}
  return <Shell title="Moderasi Review" description="Terbitkan atau sembunyikan review pembeli terverifikasi." icon={Star} total={list.data?.pagination.total??0} toolbar={<AdminDataToolbar search={list.search} onSearchChange={list.setSearch} filter={list.status} onFilterChange={list.setStatus} options={options(["ALL","PENDING","PUBLISHED","HIDDEN"])}/>}>{list.loading?<Loading/>:list.data?.items.map(item=><Card key={item.id}><CardContent className="p-4"><div className="flex justify-between gap-3"><div><strong>{item.product.name}</strong><p className="text-sm text-muted-foreground">{item.customerName} · {item.orderNumber} · {item.rating}/5</p></div><AdminStatusPill status={item.status}/></div><p className="mt-3 text-sm">{item.text}</p><div className="mt-3 flex gap-2"><Button size="sm" onClick={()=>void mutate(item.id,"PUBLISHED")}>Terbitkan</Button><Button size="sm" variant="outline" onClick={()=>void mutate(item.id,"HIDDEN")}>Sembunyikan</Button></div></CardContent></Card>)}</Shell>;
}

export function AdminReturnsPageClient(){
  const list=useAdminList<ReturnRequestItem>("/api/admin/returns");const [note,setNote]=useState("");async function status(id:string,value:string){try{await apiRequest(`/api/admin/returns/${id}`,{method:"PATCH",body:JSON.stringify({status:value,reviewNote:note||null})});toast.success("Status return diperbarui.");setNote("");await list.load();}catch(e){toast.error(e instanceof Error?e.message:"Return gagal diperbarui.");}}async function refund(id:string){try{await apiRequest(`/api/admin/returns/${id}/refund`,{method:"PATCH"});toast.success("Refund ditandai diproses.");await list.load();}catch(e){toast.error(e instanceof Error?e.message:"Refund gagal diproses.");}}
  return <Shell title="Return / RMA" description="Review bukti, kelola state return, dan proses refund manual sesuai permission." icon={RotateCcw} total={list.data?.pagination.total??0} toolbar={<AdminDataToolbar search={list.search} onSearchChange={list.setSearch} filter={list.status} onFilterChange={list.setStatus} options={options(["ALL","REQUESTED","REVIEWING","APPROVED","REJECTED","RECEIVED","CLOSED"])}/>}>{list.loading?<Loading/>:list.data?.items.map(item=><Card key={item.id}><CardContent className="p-4"><div className="flex justify-between gap-3"><div><strong>{item.orderItem.product.name}</strong><p className="text-sm text-muted-foreground">{item.order.orderNumber} · {item.user?.email} · qty {item.quantity}</p></div><div className="flex gap-2"><AdminStatusPill status={item.status}/><AdminStatusPill status={item.refundStatus}/></div></div><p className="mt-3 text-sm">{item.reason}: {item.description}</p><Input className="mt-3" placeholder="Catatan admin" value={note} onChange={e=>setNote(e.target.value)}/><div className="mt-3 flex flex-wrap gap-2">{nextReturn(item.status).map(value=><Button key={value} size="sm" variant="outline" onClick={()=>void status(item.id,value)}>{value}</Button>)}{item.refundStatus==="MANUAL_REVIEW"?<Button size="sm" onClick={()=>void refund(item.id)}>Proses refund</Button>:null}</div></CardContent></Card>)}</Shell>;
}
function nextReturn(status:string){return({REQUESTED:["REVIEWING","REJECTED"],REVIEWING:["APPROVED","REJECTED"],APPROVED:["RECEIVED"],RECEIVED:["CLOSED"]} as Record<string,string[]>)[status]??[]}

export function AdminComplaintsPageClient(){
  const list=useAdminList<ComplaintItem>("/api/admin/complaints");const [note,setNote]=useState("");async function mutate(id:string,status:string){try{await apiRequest(`/api/admin/complaints/${id}`,{method:"PATCH",body:JSON.stringify({status,resolutionNote:note||null})});toast.success("Komplain diperbarui.");setNote("");await list.load();}catch(e){toast.error(e instanceof Error?e.message:"Komplain gagal diperbarui.");}}
  return <Shell title="Manajemen Komplain" description="Tindak lanjuti kendala customer dan simpan catatan penyelesaian." icon={MessageSquareWarning} total={list.data?.pagination.total??0} toolbar={<AdminDataToolbar search={list.search} onSearchChange={list.setSearch} filter={list.status} onFilterChange={list.setStatus} options={options(["ALL","OPEN","IN_REVIEW","RESOLVED","CLOSED"])}/>}>{list.loading?<Loading/>:list.data?.items.map(item=><Card key={item.id}><CardContent className="p-4"><div className="flex justify-between gap-3"><div><strong>{item.title}</strong><p className="text-sm text-muted-foreground">{item.order.orderNumber} · {item.user?.email} · {item.category}</p></div><AdminStatusPill status={item.status}/></div><p className="mt-3 text-sm">{item.description}</p><Input className="mt-3" placeholder="Catatan penyelesaian" value={note} onChange={e=>setNote(e.target.value)}/><div className="mt-3 flex gap-2">{item.status==="OPEN"?<Button size="sm" variant="outline" onClick={()=>void mutate(item.id,"IN_REVIEW")}>Review</Button>:null}{!["RESOLVED","CLOSED"].includes(item.status)?<Button size="sm" onClick={()=>void mutate(item.id,"RESOLVED")}>Selesaikan</Button>:null}{item.status==="RESOLVED"?<Button size="sm" variant="outline" onClick={()=>void mutate(item.id,"CLOSED")}>Tutup</Button>:null}</div></CardContent></Card>)}</Shell>;
}

export function AdminArticlesPageClient(){
  const list=useAdminList<ArticleItem>("/api/admin/articles");const [editing,setEditing]=useState<ArticleItem|null|undefined>();const [saving,setSaving]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);const f=new FormData(event.currentTarget);const payload={title:f.get("title"),slug:f.get("slug"),excerpt:f.get("excerpt"),category:f.get("category"),tags:String(f.get("tags")).split(",").map(x=>x.trim()).filter(Boolean),content:f.get("content"),imageUrl:f.get("imageUrl"),status:f.get("status"),metaTitle:f.get("metaTitle"),metaDescription:f.get("metaDescription")};try{await apiRequest(editing?`/api/admin/articles/${editing.id}`:"/api/admin/articles",{method:editing?"PATCH":"POST",body:JSON.stringify(payload)});toast.success("Artikel disimpan.");setEditing(undefined);await list.load();}catch(e){toast.error(e instanceof Error?e.message:"Artikel gagal disimpan.");}finally{setSaving(false);}}
  async function archive(id:string){try{await apiRequest(`/api/admin/articles/${id}`,{method:"DELETE"});toast.success("Artikel diarsipkan.");await list.load();}catch(e){toast.error(e instanceof Error?e.message:"Artikel gagal diarsipkan.");}}
  return <Shell title="Manajemen Artikel" description="Kelola artikel tips outdoor, metadata SEO, dan status publikasi." icon={FileText} total={list.data?.pagination.total??0} toolbar={<div className="flex gap-3"><div className="flex-1"><AdminDataToolbar search={list.search} onSearchChange={list.setSearch} filter={list.status} onFilterChange={list.setStatus} options={options(["ALL","DRAFT","PUBLISHED","ARCHIVED"])}/></div><Button onClick={()=>setEditing(null)}>Tambah</Button></div>}>{list.loading?<Loading/>:list.data?.items.map(item=><Card key={item.id}><CardContent className="p-4"><div className="flex justify-between gap-3"><div><strong>{item.title}</strong><p className="text-sm text-muted-foreground">{item.category} · {item.readingTime}</p></div><AdminStatusPill status={item.status}/></div><p className="mt-3 text-sm text-muted-foreground">{item.excerpt}</p><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={()=>setEditing(item)}>Edit</Button><Button size="sm" variant="ghost" onClick={()=>void archive(item.id)}>Arsipkan</Button></div></CardContent></Card>)}
  <Dialog open={editing!==undefined} onOpenChange={open=>!open&&setEditing(undefined)}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{editing?"Edit artikel":"Tambah artikel"}</DialogTitle><DialogDescription>Konten dipisahkan menjadi paragraf berdasarkan baris kosong.</DialogDescription></DialogHeader><form className="grid gap-3" onSubmit={submit}><F label="Judul" name="title" value={editing?.title}/><F label="Slug" name="slug" value={editing?.slug}/><F label="Kategori" name="category" value={editing?.category??"Edukasi"}/><F label="Tags (pisahkan koma)" name="tags" value={editing?.tags.join(", ")}/><F label="URL gambar" name="imageUrl" value={editing?.imageUrl??""} required={false}/><F label="Meta title" name="metaTitle" value={editing?.metaTitle??""} required={false}/><F label="Meta description" name="metaDescription" value={editing?.metaDescription??""} required={false}/><div className="grid gap-2"><Label>Excerpt</Label><Textarea name="excerpt" defaultValue={editing?.excerpt} required/></div><div className="grid gap-2"><Label>Konten</Label><Textarea name="content" className="min-h-48" defaultValue={editing?.content.join("\n\n")} required/></div><div className="grid gap-2"><Label>Status</Label><select name="status" defaultValue={editing?.status??"DRAFT"} className="h-10 rounded-md border bg-background px-3">{["DRAFT","PUBLISHED","ARCHIVED"].map(x=><option key={x}>{x}</option>)}</select></div><Button disabled={saving}>{saving?<Loader2 className="animate-spin"/>:null}Simpan</Button></form></DialogContent></Dialog></Shell>;
}

function Shell({title,description,icon,total,toolbar,children}:{title:string;description:string;icon:typeof Star;total:number;toolbar:React.ReactNode;children:React.ReactNode}){return <div className="grid gap-6"><AdminPageHeader title={title} description={description}/><div className="grid gap-4 md:grid-cols-3"><AdminMetricCard title="Total" value={String(total)} note="Data sesuai filter" icon={icon}/></div>{toolbar}<div className="grid gap-4 lg:grid-cols-2">{children}</div></div>}
function Loading(){return <div className="grid min-h-40 place-items-center lg:col-span-2"><Loader2 className="animate-spin text-primary"/></div>}
function F({label,name,value,required=true}:{label:string;name:string;value?:string;required?:boolean}){return <div className="grid gap-2"><Label>{label}</Label><Input name={name} defaultValue={value} required={required}/></div>}
